# Generated by Django 5.2.7 on 2025-11-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apppermission_customuser_app_permissions_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('owner', 'Dueño'), ('seller', 'Vendedor'), ('supplier', 'Proveedor'), ('customer', 'Cliente')], default='customer', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
