# Generated by Django 5.2.7 on 2025-11-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_image_product_sizes_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text="Color principal de la prenda, ej: 'Negro', 'Azul marino'", max_length=32, null=True),
        ),
    ]
