# Generated by Django 5.2.7 on 2025-11-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text="Lista de colores, ej: ['Negro','Azul']"),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Color principal de la prenda (legacy)', max_length=32, null=True),
        ),
    ]
