# Generated by Django 5.2.7 on 2025-11-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_colors_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer'), ('U', 'Unisex')], db_index=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='kind',
            field=models.CharField(blank=True, choices=[('V', 'Vestir'), ('Z', 'Calzado')], db_index=True, max_length=1, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='inventory_c_name_546ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['gender'], name='inventory_c_gender_8788e5_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['kind'], name='inventory_c_kind_9b3575_idx'),
        ),
    ]
