# Generated by Django 5.2.7 on 2025-11-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_category_gender_category_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sizes',
            field=models.JSONField(blank=True, default=list, help_text="Lista de tallas sugeridas para la categoría, ej: ['S','M','L']"),
        ),
    ]
