# Generated by Django 5.2.7 on 2025-11-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_category_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer'), ('U', 'Unisex')], help_text='Género del producto (si no se define, se asume el de la categoría)', max_length=1, null=True),
        ),
    ]
