# Generated by Django 5.2.7 on 2025-11-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='formatted_address',
            field=models.TextField(blank=True, help_text='Dirección formateada retornada por la API de mapas', null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud en formato decimal (-90 a 90)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud en formato decimal (-180 a 180)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='place_id',
            field=models.CharField(blank=True, help_text='Google Place ID si se seleccionó desde el mapa', max_length=128, null=True),
        ),
    ]
