# Generated by Django 5.2.7 on 2025-11-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_address_formatted_address_address_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, help_text='Nombre para identificar esta ubicación (ej: Casa, Trabajo)', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
