# Generated by Django 5.2.7 on 2025-11-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_add_inventory_deducted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
