# Generated by Django 5.2.7 on 2025-11-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderitem_product_alter_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size_cache',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
